# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Pod-Extract-URI
version:      0.1
version_from: lib/Pod/Extract/URI.pm
installdirs:  site
requires:
    Carp:                          0
    Pod::Parser:                   0
    Test::More:                    0
    URI::Find:                     0
    URI::Find::Schemeless:         0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
